name: test

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

concurrency: ci-${{ github.ref }}

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  test-another-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
