name: profiler-run
on:
    workflow_run:
      workflows: ["aws-deploy"] # Trigger this workflow only after aws-deploy is completed 
      types: [completed]
    workflow_dispatch: # Allow manually triggering the workflow
jobs:
    trigger-profiler:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: Repository Dispatch
              uses: peter-evans/repository-dispatch@v3
              with:
                token: ${{ secrets.ACCESS_PROFILER }}
                repository: Sage-Bionetworks/schematic_profiler
                event-type: trigger-profiler
